#THIS PROJECT READS THE EXCEL FILE FROM THE INPUT FOLDER AND FINDS THE MOST POPULATED
#CITIES OF THE COUNTRIES LISTED IN IT, THEN SHOWS THEM ON A MAP WHICH YOU CAN ACCESS IN THE MAP.R FILE
#THE GUI USED IN THIS PROGRAM ASKS YOU FOR THE NAME OF A COUNTRY OF YOUR CHOICE THEN SHOWS IT ON THE MAP
#YOU CAN EITHER TYPE IN A COUNTRY NAME OR THE WORD "all" 
#(THE EXCEL FILE DOES NOT CONTAIN COMPLETELY UP TO DATE INFORMATION)


if(!exists("number_of_runs")){
  source("data_collector.r", echo = TRUE)
}

#GUI
searched_country <- dlgInput("TELL ME THE NAME OF A COUNTRY! THIS MAP WILL TELL YOU IT'S MOST POPULATED CITY!
IF YOU'D LIKE TO SEE THE WHOLE MAP TYPE: all"
, Sys.info()["searched_country"])$res


#CHECKING WHICH MAP TYPE TO SHOW
if(searched_country == "all"){
  source("map.r", echo = TRUE)
}else{
  source("spec_map.r", echo = TRUE)
}

searched_country <- ""
